spring:
  profiles:
    include:
      - domain
      - common
      - infrastructure

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: prometheus, health


jwt:
  secret: ENC(hQLPUuufo6+rX3SKuCA1WOTUqjyLREZsBF1q4dFrB2+WLMQNVyGhB4d2zskhI6sdCWgDaPBDABZFIg6nk3eLtZErUieH1I33)
  expiration-period: ENC(akNgWoo0R4MHHtv0+2iBQw==)
