jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

jwt:
  secret: ENC(hQLPUuufo6+rX3SKuCA1WOTUqjyLREZsBF1q4dFrB2+WLMQNVyGhB4d2zskhI6sdCWgDaPBDABZFIg6nk3eLtZErUieH1I33)
  expiration-period: ENC(akNgWoo0R4MHHtv0+2iBQw==)

oauth2:
  properties:
    kakao:
      client-id: ENC(Bu6Yp54XiIon/58VweoWenQ4k563D+clcP69xlGmBgcILWmLm86i6D+ZG+AJw5do)
      client-secret: ENC(/Lx2UYfDcEMZRVs0JaloT6NxiH9TjtW9sYoz36TAWjdHH/aPXY368Sm+7lso1LkC)
      redirect-uri: http://localhost:8080/api/auth/login/oauth/kakao
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      member-info-key-word-request:
        email-key-word: kakao_account.email
        nickname-key-word: kakao_account.profile.nickname
